[project]
name = "tiny-s3"
version = "0.1.0"
description = "Tiny S3 client"
authors = [
    {name = "Sergey Abramov", email = "spabramov@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
